// API 路径 -> 权限点映射（null = 登录即可；undefined = 开发期放行）
module.exports = {
  'GET /api/auth/me': null,
  'GET /api/auth/permissions': null,
  'POST /api/auth/logout': null,

  'GET /api/proj/org/department/list': 'org:department:view',
  'GET /api/proj/org/department': 'org:department:view',
  'POST /api/proj/org/department': 'org:department:update',
  'PUT /api/proj/org/department': 'org:department:update',
  'DELETE /api/proj/org/department': 'org:department:update',
  'POST /api/proj/org/department/disable': 'org:department:update',

  'GET /api/proj/org/user/list': 'org:department:view',
  'GET /api/proj/org/user': 'org:department:view',
  'POST /api/proj/org/user': 'org:user:create',
  'PUT /api/proj/org/user': 'org:user:update',
  'POST /api/proj/org/user/reset_password': 'org:user:update',
  'POST /api/proj/org/user/lock': 'org:user:disable',
  'POST /api/proj/org/user/unlock': 'org:user:update',

  'GET /api/proj/org/role/list': 'org:department:view',
  'GET /api/proj/org/role': 'org:department:view',
  'POST /api/proj/org/role': 'org:role:create',
  'PUT /api/proj/org/role': 'org:role:update',
  'GET /api/proj/org/role_permissions': 'org:role:permission:update',
  'POST /api/proj/org/role_permissions': 'org:role:permission:update',

  'GET /api/proj/permission/list': 'org:role:permission:update',
  'GET /api/proj/permission/tree': 'org:role:permission:update',

  'GET /api/proj/store/list': 'store:view',
  'GET /api/proj/store': 'store:view',
  'POST /api/proj/store': 'store:create',
  'PUT /api/proj/store': 'store:update',
  'DELETE /api/proj/store': 'store:disable',

  'GET /api/proj/category/list': 'product:view',
  'GET /api/proj/category': 'product:view',
  'POST /api/proj/category': 'product:create',
  'PUT /api/proj/category': 'product:update',

  'GET /api/proj/brand/list': 'product:view',
  'GET /api/proj/brand': 'product:view',
  'POST /api/proj/brand': 'product:create',
  'PUT /api/proj/brand': 'product:update',

  'GET /api/proj/product/list': 'product:view',
  'GET /api/proj/product': 'product:view',
  'POST /api/proj/product': 'product:create',
  'PUT /api/proj/product': 'product:update',
  'DELETE /api/proj/product': 'product:delete',

  'GET /api/proj/product/sku_list': 'product:view',
  'POST /api/proj/product/sku': 'product:update',
  'PUT /api/proj/product/sku': 'product:update',
  'DELETE /api/proj/product/sku': 'product:update',

  'POST /api/proj/product/submit_review': 'product:submit_review',
  'POST /api/proj/product/on_sale': 'product:on_sale',
  'POST /api/proj/product/off_sale': 'product:off_sale',

  'GET /api/proj/warehouse/list': 'warehouse:view',
  'GET /api/proj/warehouse': 'warehouse:view',
  'POST /api/proj/warehouse': 'warehouse:create',
  'PUT /api/proj/warehouse': 'warehouse:update',
  'GET /api/proj/warehouse/layout': 'warehouse:view',
  'GET /api/proj/warehouse/risk_map': 'warehouse:view',

  'GET /api/proj/warehouse/location/list': 'warehouse:view',
  'GET /api/proj/warehouse/location': 'warehouse:view',
  'POST /api/proj/warehouse/location': 'warehouse:location:update',
  'PUT /api/proj/warehouse/location': 'warehouse:location:update',

  'GET /api/proj/stock/list': 'stock:view',
  'GET /api/proj/stock/location_list': 'stock:view',
  'GET /api/proj/stock/location/list': 'stock:view',
  'GET /api/proj/stock/log_list': 'stock:view',
  'POST /api/proj/stock/inbound': 'stock:inbound',
  'POST /api/proj/stock/lock': 'stock:lock',
  'POST /api/proj/stock/unlock': 'stock:lock',
  'POST /api/proj/stock/outbound': 'stock:outbound',

  'GET /api/proj/order/list': 'order:view',
  'GET /api/proj/order': 'order:view',
  'POST /api/proj/order/import': 'order:import',
  'GET /api/proj/order/import_result': 'order:view',
  'POST /api/proj/order/mock_pay': 'order:pay',
  'POST /api/proj/order/allocate': 'order:allocate',

  'GET /api/proj/shipment/list': 'shipment:view',
  'GET /api/proj/shipment': 'shipment:view',
  'POST /api/proj/shipment/create_from_order': 'shipment:create',
  'POST /api/proj/shipment/start_pick': 'shipment:pick',
  'POST /api/proj/shipment/confirm_pick': 'shipment:pick',
  'POST /api/proj/shipment/ship': 'shipment:ship',
  'GET /api/proj/shipment/picking_route': 'shipment:view',
}
