exports.up = async (knex) => {
  await knex.schema.createTable('customers', (t) => {
    t.string('customer_id', 64).primary()
    t.string('tenant_id', 64).notNullable().index()
    t.string('customer_name', 128).notNullable()
    t.string('phone', 32)
    t.string('address', 255)
    t.timestamps(true, true)
  })

  await knex.schema.createTable('order_import_batches', (t) => {
    t.string('batch_id', 64).primary()
    t.string('tenant_id', 64).notNullable().index()
    t.string('file_name', 255)
    t.integer('total_rows').notNullable().defaultTo(0)
    t.integer('success_rows').notNullable().defaultTo(0)
    t.integer('fail_rows').notNullable().defaultTo(0)
    t.string('status', 32).notNullable().defaultTo('processing')
    t.string('created_by', 64)
    t.timestamp('created_at').defaultTo(knex.fn.now())
  })

  await knex.schema.createTable('order_import_errors', (t) => {
    t.string('error_id', 64).primary()
    t.string('batch_id', 64).notNullable().index()
    t.integer('row_no').notNullable()
    t.string('reason', 512).notNullable()
    t.text('raw_data')
    t.timestamp('created_at').defaultTo(knex.fn.now())
  })

  await knex.schema.createTable('orders', (t) => {
    t.string('order_id', 64).primary()
    t.string('tenant_id', 64).notNullable().index()
    t.string('order_no', 64).notNullable()
    t.string('store_id', 64).notNullable().index()
    t.string('customer_id', 64).nullable().index()
    t.string('warehouse_id', 64).nullable().index()
    t.string('status', 32).notNullable().defaultTo('pending_payment')
    t.decimal('total_amount', 12, 2).notNullable().defaultTo(0)
    t.string('currency', 8).notNullable().defaultTo('CNY')
    t.string('import_batch_id', 64).nullable()
    t.string('remark', 255)
    t.timestamps(true, true)
    t.unique(['tenant_id', 'order_no'])
    t.index(['tenant_id', 'status'])
    t.index(['tenant_id', 'store_id'])
  })

  await knex.schema.createTable('order_items', (t) => {
    t.string('item_id', 64).primary()
    t.string('tenant_id', 64).notNullable().index()
    t.string('order_id', 64).notNullable().index()
    t.string('sku_id', 64).notNullable()
    t.string('sku_code', 64).notNullable()
    t.string('product_name', 255)
    t.integer('qty').notNullable()
    t.decimal('unit_price', 12, 2).notNullable().defaultTo(0)
    t.decimal('amount', 12, 2).notNullable().defaultTo(0)
    t.string('lock_id', 64).nullable()
    t.timestamps(true, true)
  })

  await knex.schema.createTable('order_status_logs', (t) => {
    t.string('log_id', 64).primary()
    t.string('tenant_id', 64).notNullable().index()
    t.string('order_id', 64).notNullable().index()
    t.string('from_status', 32)
    t.string('to_status', 32).notNullable()
    t.string('remark', 255)
    t.string('operator_id', 64)
    t.timestamp('created_at').defaultTo(knex.fn.now())
    t.index(['tenant_id', 'order_id', 'created_at'])
  })

  await knex.schema.createTable('payments', (t) => {
    t.string('payment_id', 64).primary()
    t.string('tenant_id', 64).notNullable().index()
    t.string('order_id', 64).notNullable().index()
    t.decimal('amount', 12, 2).notNullable()
    t.string('pay_method', 32).notNullable().defaultTo('online')
    t.string('status', 32).notNullable()
    t.timestamp('paid_at').nullable()
    t.timestamps(true, true)
  })

  await knex.schema.createTable('shipments', (t) => {
    t.string('shipment_id', 64).primary()
    t.string('tenant_id', 64).notNullable().index()
    t.string('order_id', 64).notNullable().index()
    t.string('warehouse_id', 64).notNullable().index()
    t.string('shipment_no', 64).notNullable()
    t.string('status', 32).notNullable().defaultTo('created')
    t.timestamps(true, true)
    t.unique(['tenant_id', 'shipment_no'])
    t.index(['tenant_id', 'status'])
  })

  await knex.schema.createTable('shipment_items', (t) => {
    t.string('item_id', 64).primary()
    t.string('tenant_id', 64).notNullable().index()
    t.string('shipment_id', 64).notNullable().index()
    t.string('sku_id', 64).notNullable()
    t.integer('qty').notNullable()
    t.string('suggested_location_id', 64).nullable()
    t.string('picked_location_id', 64).nullable()
    t.timestamps(true, true)
  })

  await knex.schema.createTable('picking_tasks', (t) => {
    t.string('task_id', 64).primary()
    t.string('tenant_id', 64).notNullable().index()
    t.string('shipment_id', 64).notNullable().index()
    t.string('status', 32).notNullable().defaultTo('pending')
    t.string('picker_id', 64).nullable()
    t.timestamp('started_at').nullable()
    t.timestamp('finished_at').nullable()
    t.timestamps(true, true)
  })

  await knex.schema.createTable('logistics', (t) => {
    t.string('logistics_id', 64).primary()
    t.string('tenant_id', 64).notNullable().index()
    t.string('shipment_id', 64).notNullable().index()
    t.string('carrier', 64).nullable()
    t.string('tracking_no', 128).nullable()
    t.timestamp('shipped_at').nullable()
    t.timestamps(true, true)
  })
}

exports.down = async (knex) => {
  await knex.schema.dropTableIfExists('logistics')
  await knex.schema.dropTableIfExists('picking_tasks')
  await knex.schema.dropTableIfExists('shipment_items')
  await knex.schema.dropTableIfExists('shipments')
  await knex.schema.dropTableIfExists('payments')
  await knex.schema.dropTableIfExists('order_status_logs')
  await knex.schema.dropTableIfExists('order_items')
  await knex.schema.dropTableIfExists('orders')
  await knex.schema.dropTableIfExists('order_import_errors')
  await knex.schema.dropTableIfExists('order_import_batches')
  await knex.schema.dropTableIfExists('customers')
}
